# Métodos directos de resolución de sistemas - algoritmos generales

## Método de la eliminación de Gauss

### Introducción

La eliminación de Gauss es el método más conocido para resolver sistemas de ecuaciones. Consta de dos partes: la fase de eliminación y la fase de sustitución. Como se ha indicado en la introducción, la fase de eliminación pretende transformar el sistema en uno equivalente con la forma $\mathbf{U} \mathbf{x} = \mathbf{c}$. A continuación, las ecuaciones se resuelven por sustitución hacia atrás. Para ilustrar este procedimiento, resolveremos el siguiente sistema de ecuaciones:
$$
\begin{gathered}
4 x_1-2 x_2+x_3=11    & \qquad (a)\\
-2 x_1+4 x_2-2 x_3=-16& \qquad (b) \\
x_1-2 x_2+4 x_3=17& \qquad (c)
\end{gathered}
$$

#### Fase de eliminación

La fase de eliminación sólo utiliza una de las operaciones elementales descritas en la introducción: multiplicar una ecuación (por ejemplo, la ecuación $j$) por una constante $\lambda$ y restarla de otra ecuación (ecuación $i$). La representación simbólica de esta operación es:

$$
\text { Ec. } (i) \leftarrow \text { Ec. } (i) - \lambda \times \text { Ec. } (j)
$$

La ecuación que se resta (es decir, la ecuación $(j)$) se llama *ecuación pivote*.

Comenzamos la eliminación tomando la ecuación $(a)$ como ecuación pivote y eligiendo los multiplicadores $\lambda$ apropiados para eliminar $x_1$ de las ecuaciones $(b)$ y $(c)$:


Tras esta transformación, las ecuaciones se convierten en

$$
\begin{aligned}
4 x_1-2 x_2+x_3 &=11       & \qquad (a)\\
3 x_2-1.5 x_3 &=-10.5      & \qquad (b) \\
-1.5 x_2+3.75 x_3 &=14.25  & \qquad (c)
\end{aligned}
$$


Esto completa la primera pasada. Ahora elegimos $(b)$ como ecuación pivote y eliminamos $x_2$ de (c):

$$\text{Ec. } (c) \leftarrow \text{ Ec. } (c) -(-0.5) \times \text{ Ec. } (b)$$

lo que da lugar a las ecuaciones


La fase de eliminación ha concluido. Las ecuaciones originales se han sustituido por ecuaciones equivalentes que pueden resolverse fácilmente mediante la sustitución hacia atrás.

$$
\begin{aligned}
4 x_1-2 x_2+x_3 &=11 & \qquad (a)\\
3 x_2-1.5 x_3 &=-10.5& \qquad (b) \\
3 x_3 &=9& \qquad (c)
\end{aligned}
$$
Como se comentaba en la introducción, el uso de la matriz de coeficientes aumentada es más conveniente para realizar los cálculos. Así, las ecuaciones originales se escribirían como

$$
\left[\begin{array}{rrr|r}
4 & -2 & 1 & 11 \\
-2 & 4 & -2 & -16 \\
1 & -2 & 4 & 17
\end{array}\right]
$$
y las ecuaciones equivalentes producidas por la primera y la segunda pasada de la eliminación de Gauss serían:

$$
\left[\begin{array}{rrr|r}
4 & -2 & 1 & 11.00 \\
0 & 3 & -1.5 & -10.50 \\
0 & -1.5 & 3.75 & 14.25
\end{array}\right]
$$
$$
\left[\begin{array}{ccc|r}
4 & -2 & 1 & 11.0 \\
0 & 3 & -1.5 & -10.5 \\
0 & 0 & 3 & 9.0
\end{array}\right]
$$

Es importante recordar que la operación elemental de multiplicar una ecuación por un factor y restarla a otra ecuación no modifica el valor del determinante de la matriz. Esto es una ventaja, porque el determinante de una matriz triangular es muy fácil de calcular: es el producto de los elementos de la diagonal principal. Es decir:

$$
|\mathbf{A}|=|\mathbf{U}|=U_{11} \times U_{22} \times \cdots \times U_{n n}
$$

 
#### Fase de sustitución hacia atrás

Las incógnitas pueden calcularse ahora por sustitución hacia atrás, tal y como se explicó en la introducción. Resolviendo las ecuaciones $(c)$, $(b)$ y $(a)$ en ese orden, obtenemos:
\begin{aligned}
&x_3=9 / 3=3 \\
&x_2=\left(-10.5+1.5 x_3\right) / 3=[-10.5+1.5(3)] / 3=-2 \\
&x_1=\left(11+2 x_2-x_3\right) / 4=[11+2(-2)-3] / 4=1
\end{aligned}


## Algoritmo del método de Gauss

A continuación se formalizará el algoritmo descrito anteriormente para poder ser implementado. Se puede demostrar que la fase de eliminación es $\mathcal{O}\left( n^3 \right)$, mientras que la fase de sustitución es $\mathcal{O}\left( n^2 \right)$.

### Fase de eliminación

Fijémonos en las ecuaciones en algún momento de la fase de eliminación. Supongamos que las primeras $k$ filas de $\mathbf{A}$ ya han sido transformadas a la forma triangular superior. Por lo tanto, la ecuación pivote actual es la $k$-ésima ecuación, y todas las ecuaciones por debajo de ella están aún por transformar. Esta situación se representa con la siguiente matriz de coeficientes aumentada. Obsérvese que, en este punto, los coeficientes de $\mathbf{A}$ no son los coeficientes del sistema original (excepto la primera ecuación), porque han sido alterados por el procedimiento de eliminación. Lo mismo ocurre con las componentes del vector de términos independientes $\mathbf{b}$.

$$
\left[\begin{array}{ccccccccc|c}
A_{11} & A_{12} & A_{13} & \cdots & A_{1 k} & \cdots & A_{1 j} & \cdots & A_{1 n} & b_1 \\
0 & A_{22} & A_{23} & \cdots & A_{2 k} & \cdots & A_{2 j} & \cdots & A_{2 n} & b_2 \\
0 & 0 & A_{33} & \cdots & A_{3 k} & \cdots & A_{3 j} & \cdots & A_{3 n} & b_3 \\
\vdots & \vdots & \vdots & & \vdots & & \vdots & & \vdots & \vdots \\
0 & 0 & 0 & \cdots & A_{k k} & \cdots & A_{k j} & \cdots & A_{k n} & b_k \\
\hline \vdots & \vdots & \vdots & & \vdots & & \vdots & & \vdots & \vdots \\
0 & 0 & 0 & \cdots & A_{i k} & \cdots & A_{i j} & \cdots & A_{i n} & b_i \\
\vdots & \vdots & \vdots & & \vdots & & \vdots & & \vdots & \vdots \\
0 & 0 & 0 & \cdots & A_{n k} & \cdots & A_{n j} & \cdots & A_{n n} & b_n
\end{array}\right] \begin{array}{l} \\ \\ \leftarrow \text { fila pivote } \\ \\ \\ \leftarrow \text { fila a\\ transformar} \\ \end{array}
$$

Sea la fila $i$-ésima una fila (por debajo de la ecuación pivote) que va a ser transformada, lo que significa que el elemento $A_{ik}$ va a ser eliminado. Podemos conseguirlo multiplicando la fila pivote por $\lambda = A_{ik} / A_{kk}$ y restándosela a la fila $i$-ésima. Los cambios correspondientes en la $i$-ésima fila son por tanto:
$$
\begin{aligned}
A_{i j} & \leftarrow A_{i j}-\lambda A_{k j}, \quad j=k, k+1, \ldots, n \\
b_i & \leftarrow b_i-\lambda b_k
\end{aligned}
$$
Para transformar toda la matriz de coeficientes a la forma triangular superior, los índices $k$ e $i$ de las ecuaciones de transformación anteriores deben tener los rangos $k = 1, 2, \dots, n - 1$ (elección de la fila pivote), e $i = k + 1, k + 2, \dots , n$ (elección de la fila que se va a transformar).

La descripción del algoritmo está casi completa, a falta de dos detalles:
 - Si un cierto $A_{ik}$ (el primer elemento de la fila a transformar) resulta ser cero, se salta la transformación de esa fila $i$.
 - El índice $j$ en las ecuaciones de transformación anteriores podría comenzar en $k + 1$ en lugar de en $k$, de forma que los $A_{ik}$ no se fijan en cero, sino que conservan su valor original. Esto puede hacerse para ahorrar operaciones: como en la fase de solución nunca se accede a la parte triangular inferior de la matriz de coeficientes, su contenido es irrelevante.


**Ejercicio 1 -** Programa el algoritmo de eliminación del método de Gauss, con las consideraciones anteriores.

In [1]:
import numpy as np #type: ignore 

def row_lineal_comb(A, i, j, k):

    ''' i es la posicion de la linea a la que multiplicas por k
    j es el indice de la linea que estamos modificando
    k es el valor por el cual multiplicamos a A[i]

    devuelve uan copia de la matriz 
    '''

    A_copy = np.copy(A)
    ai = np.copy(A[i])

    A_copy[j] = A_copy[j] + ai * k

    return A_copy

In [2]:
A = np.array([[4, -2, 1],
             [-2, 4, -2],
             [1, -2, 4]], dtype = float)

b = np.array([11, -16, 17])

A_ampliada = np.column_stack((A, b))
A_ampliada

array([[  4.,  -2.,   1.,  11.],
       [ -2.,   4.,  -2., -16.],
       [  1.,  -2.,   4.,  17.]])

In [3]:
print(row_lineal_comb(A_ampliada, 0, 1, 1/2))

[[  4.   -2.    1.   11. ]
 [  0.    3.   -1.5 -10.5]
 [  1.   -2.    4.   17. ]]


In [4]:
# def row_lineal_comb_modify(A, i, j, k):
#     '''
#     Realiza una combinación lineal entre filas de la matriz A:
#     - i: Índice de la fila base que se multiplica por k
#     - j: Índice de la fila que se modifica
#     - k: Factor por el cual se multiplica la fila i antes de sumarla a la fila j
#     '''
#     A[j] -= A[i] * k

In [3]:
def gauss_U(A: np.array, func = row_lineal_comb) -> np.array:

    '''se le pasa la matriz A 
    una funcion func que se encargue de hacer al combinacion lineal: A[j] = A[j] + A[i] * k

    puede devolverte la matriz triangular superior de A 
    tambien puede devolver la triangular de A ampliada con el vector/matriz solución

    A -> U
    A|B -> U|C
    '''
    A_copy = np.copy(A)
    
    for i in range(len(A_copy)): #iteramos cada fila
        #print(i)
        for j in range(i +1, len(A_copy)): #iteramos solo sobre las filas que estan debajo del pivote
            #print(j)
            if A_copy[i, i] == 0:
                continue
            k =  A_copy[j, i]/ A_copy[i, i]
            #print(k)
            A_copy = func(A_copy, i, j, -k)
            #print(A)


    return A_copy


A = np.array([[4, -2, 1],
             [-2, 4, -2],
             [1, -2, 4]], dtype = float)

b = np.array([11, -16, 17])

A_ampliada = np.column_stack((A, b))


print(A_ampliada)
print(gauss_U(A_ampliada))
print(A)
print(gauss_U(A))

[[  4.  -2.   1.  11.]
 [ -2.   4.  -2. -16.]
 [  1.  -2.   4.  17.]]
[[  4.   -2.    1.   11. ]
 [  0.    3.   -1.5 -10.5]
 [  0.    0.    3.    9. ]]
[[ 4. -2.  1.]
 [-2.  4. -2.]
 [ 1. -2.  4.]]
[[ 4.  -2.   1. ]
 [ 0.   3.  -1.5]
 [ 0.   0.   3. ]]


### Fase de sustitución hacia atrás

Tras la eliminación de Gauss, la matriz de coeficientes aumentada tendrá la forma:

$$
[\mathbf{A} \mid \mathbf{b}]=\left[\begin{array}{ccccc|c}
A_{11} & A_{12} & A_{13} & \cdots & A_{1 n} & b_1 \\
0 & A_{22} & A_{23} & \cdots & A_{2 n} & b_2 \\
0 & 0 & A_{33} & \cdots & A_{3 n} & b_3 \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
0 & 0 & 0 & \cdots & A_{n n} & b_n
\end{array}\right]
$$

La última ecuación, $A_{nn} x_n = b_n$ se resuelve primero, dando como resultado:

$$
x_n = \frac{b_n}{A_{nn}}
$$

Consideremos ahora un momento genérico de la etapa de la sustitución hacia atrás en el que ya se ha calculado $x_n , x_{n−1}, \dots , x_{k+1}$ ya han sido calculados (en ese orden), y vamos a determinar $x_k$ a partir de la $k$-ésima ecuación:

$$
A_{k k} x_k+A_{k, k+1} x_{k+1}+\cdots+A_{k n} x_n=b_k
$$

y su solución es:

$$
x_k=\left(b_k-\sum_{j=k+1}^n A_{k j} x_j\right) \frac{1}{A_{k k}}, \quad k=n-1, n-2, \ldots, 1
$$



**Ejercicio 2 -** Completa el algoritmo del método de Gauss comenzado en el ejercicio 1, programando ahora la fase de sustitución hacia atrás, teniendo en cuenta las consideraciones anteriores.

In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)  # (1*4) + (2*5) + (3*6) = 32
print(result)  # Salida: 32
print()

A = np.array([[1, 2, 3],
              [4, 5, 6]])
x = np.array([1, 0, -1])
result = np.dot(A, x)  # [(1*1 + 2*0 + 3*(-1)), (4*1 + 5*0 + 6*(-1))]
print(result)  # Salida: [-2, -2]
print()

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
result = np.dot(A, B)
print(result)

A @ B  # Igual que np.dot(A, B)


32

[-2 -2]

[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

In [7]:
A = np.array([[4, -2, 1],
             [-2, 4, -2],
             [1, -2, 4]], dtype = float)

b = np.array([11, -16, 17])

solution = np.linalg.solve(A, b) 
solution


array([ 1., -2.,  3.])

In [8]:
A_ampliada = np.column_stack((A, b))
print(A_ampliada)

U_ampliada = gauss_U(A_ampliada)
A_triangulada = U_ampliada[:, 0:-1]
b_transformado = U_ampliada[:, -1]
print()
print(A_triangulada)
print()
print(b_transformado)


solution = np.linalg.solve(A_triangulada, b_transformado)
solution


[[  4.  -2.   1.  11.]
 [ -2.   4.  -2. -16.]
 [  1.  -2.   4.  17.]]

[[ 4.  -2.   1. ]
 [ 0.   3.  -1.5]
 [ 0.   0.   3. ]]

[ 11.  -10.5   9. ]


array([ 1., -2.,  3.])

In [4]:
def backward_sustitusion(U, c):
    '''
    the input is an upper triangular matrix U which dimension is nxn
    and c vector which contains the results, variable dimension
    the output is vector x, which initialy contained the unkwons, with the solution
    '''
    A_copy = np.copy(U)
    b_copy = np.copy(c)
    
    n = len(c)

    x = np.zeros((n,))


    for i in range(n-1, -1, -1):
        total_sum = 0
        for j in range(i+1, n):
            total_sum += A_copy[i, j] * x[j]

        x[i] = (b_copy[i] - total_sum) / A_copy[i, i]


    return x

A = np.array([[4, -2, 1],
             [-2, 4, -2],
             [1, -2, 4]], dtype = float)

b = np.array([11, -16, 17])

A_ampliada = np.column_stack((A, b))
U_extended = gauss_U(A_ampliada)

A_echelon = U_extended[:, 0:-1]
b_transformed = U_extended[:, -1]
print(b_transformed)

backward_sustitusion(A_echelon, b_transformed)


[ 11.  -10.5   9. ]


array([ 1., -2.,  3.])

### Múltiples sistemas de ecuaciones

A menudo es necesario resolver las ecuaciones $\mathbf{A} \mathbf{x} = \mathbf{b}$ para varios vectores de términos independientes. Sea $m$ el número de tales vectores de términos independientes, denotados por $b_1, b_2, \dots, b_m$ , y sus correspondientes vectores solución $x_1, x_2, \dots, x_m$ . Denotamos conjuntos de los múltiples sistemas de ecuaciones por $\mathbf{A} \mathbf{X} = \mathbf{B}$, donde
$$
\mathbf{X}=\left[\begin{array}{llll}
\mathbf{x}_1 & \mathbf{x}_2 & \cdots & \mathbf{x}_m
\end{array}\right] \quad \mathbf{B}=\left[\begin{array}{llll}
\mathbf{b}_1 & \mathbf{b}_2 & \cdots & \mathbf{b}_m
\end{array}\right]
$$
son matrices $n \times m$ cuyas columnas son los vectores solución y los vectores de términos independientes, respectivamente.

Una forma económica de tratar este conjunto de sistemas de ecuaciones durante la fase de eliminación es incluir todos los $m$ vectores de términos independientes en la matriz de coeficientes aumentada, de forma que se transformen simultáneamente con la matriz de coeficientes. A continuación, las soluciones se obtienen por sustitución hacia atrás de la manera habitual, vector a vector. De esta forma, el algoritmo no se complica demasiado. Sin embargo, el método de descomposición LU descrito posteriormente, es más versátil en el manejo de múltiples sistemas de ecuaciones.

**Ejercicio 3 -** Utiliza el método de Gauss para varios sistemas de ecuaciones
para resolver las ecuaciones $\mathbf{A} \mathbf{X} = \mathbf{B}$, donde

$$
\mathbf{A}=\left[\begin{array}{rrr}
6 & -4 & 1 \\
-4 & 6 & -4 \\
1 & -4 & 6
\end{array}\right] \quad \mathbf{B}=\left[\begin{array}{rr}
-14 & 22 \\
36 & -18 \\
6 & 7
\end{array}\right]
$$

In [10]:
A = np.array([[6, -4, 1],
              [-4, 6, -4],
              [1, -4, 6]])

B = np.array([[-14, 22], 
              [36, -18],
              [6, 7]])

A_concat_B = np.column_stack((A, B))
print(A_concat_B)
gauss_A_B = gauss_U(A_concat_B)
print(gauss_A_B)

[[  6  -4   1 -14  22]
 [ -4   6  -4  36 -18]
 [  1  -4   6   6   7]]
[[  6  -4   1 -14  22]
 [  0   3  -3  26  -3]
 [  0   0   2  34   0]]


In [11]:
len(B[0])

2

In [12]:
B.shape

(3, 2)

In [13]:
np.zeros(B.shape)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
def backward_sustitusion_p_systems(A, B):
    '''
    the input is an upper triangular matrix A which dimension is nxn
    and B matrix which contains the results, its dimension is nxp
    the output is matrix X, which initialy contained the unkwons, with the solution
    '''
    A_copy = np.copy(A)
    B_copy = np.copy(B)
    
    n = len(A)
    p = len(B[0])

    X = np.zeros(B.shape)

    for s in range(p):
        for i in range(n-1, -1, -1):
            total_sum = 0
            for j in range(i+1, n):
                total_sum += A_copy[i, j] * X[j, s]

            X[i, s] = (B_copy[i, s] - total_sum) / A_copy[i, i]

    return X


A = np.array([[6, -4, 1],
              [-4, 6, -4],
              [1, -4, 6]])

B = np.array([[-14, 22], 
              [36, -18],
              [6, 7]])

A_concat_B = np.column_stack((A, B))
#print(A_concat_B)
gauss_A_B = gauss_U(A_concat_B)
#print(gauss_A_B)

A_triang = gauss_A_B[:, 0:-2]
B_mod = gauss_A_B[:, 3:]

backward_sustitusion_p_systems(A_triang, B_mod)

array([[11.94444444,  3.        ],
       [25.66666667, -1.        ],
       [17.        ,  0.        ]])

In [ ]:
# A = np.array([[4, -2, 1],
#              [-2, 4, -2],
#              [1, -2, 4]], dtype = float)

# b = np.array([11, -16, 17])

# A_ampliada = np.column_stack((A, b))
# U_extended = gauss_U(A_ampliada)

# A_echelon = U_extended[:, 0:-1]
# b_transformed = U_extended[:, -1]
# print(b_transformed)

# backward_sustitusion(A_echelon, b_transformed)



# B.shape[0] = len(B[0])??

**Ejercicio 4 -** Extiende la implementación del método de Gauss realiza en los ejercicio 1 y 2 para que se pueda trabajar con múltiples sistemas de ecuaciones, $\mathbf{A} \mathbf{X} = \mathbf{B}$.

**Ejercicio 5 -** Una matriz $n \times n$ de Vandermode, $\mathbf{A}$ se define como

$$
A_{i j}=v_i^{n-j}, \quad i=1,2, \ldots, n, \quad j=1,2, \ldots, n
$$

donde $v$ es un vector. Utiliza las funciones implementadas anteriormente para resolver sistemas de ecuaciones por el método de Guass para calcular la solución de $\mathbf{A}\mathbf{x} = \mathbf{b}$, donde $\mathbf{A}$ es una matriz de Vandermode $6 \times 6$ generada a partir del vector
$$
\mathbf{v}=\left[\begin{array}{llllll}
1.0 & 1.2 & 1.4 & 1.6 & 1.8 & 2.0
\end{array}\right]^T
$$
y
$$
\mathbf{b}=\left[\begin{array}{llllll}
0 & 1 & 0 & 1 & 0 & 1
\end{array}\right]^T
$$
Evalúe también la precisión de la solución (las matrices de Vandermode tienden a estar mal condicionadas).


In [18]:
import numpy as np

x = [2, 3, 4]
V = np.vander(x, increasing=True) 
print(V)
print()
V = np.vander(x, increasing=False) 
print(V)


[[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]

[[ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


In [28]:
def vandermode_matrix(v):
    '''
    the input is a vector, v, wich dimension in n,.

    tthe output is vandermode matrix A
    '''

    n = len(v)

    A = np.ones((n, n))

    for i in range(1, n):
        A[:, i] = v ** i

    return A

v = np.array([1.0, 1.2, 1.4, 1.6, 1.8, 2.0])
vander_A = vandermode_matrix(v)
vander_A

array([[ 1.     ,  1.     ,  1.     ,  1.     ,  1.     ,  1.     ],
       [ 1.     ,  1.2    ,  1.44   ,  1.728  ,  2.0736 ,  2.48832],
       [ 1.     ,  1.4    ,  1.96   ,  2.744  ,  3.8416 ,  5.37824],
       [ 1.     ,  1.6    ,  2.56   ,  4.096  ,  6.5536 , 10.48576],
       [ 1.     ,  1.8    ,  3.24   ,  5.832  , 10.4976 , 18.89568],
       [ 1.     ,  2.     ,  4.     ,  8.     , 16.     , 32.     ]])

In [32]:
b = np.array([0, 1, 0, 1, 0, 1])

vander_A_b = np.column_stack((vander_A, b))

triangular_vander = gauss_U(vander_A_b)

sol = backward_sustitusion(triangular_vander[:, :-1], triangular_vander[:, -1])
print(sol)
len(sol)

[ -2751.           9709.33333333 -13499.99999999   9250.
  -3125.            416.66666667]


6

## Métodos basados en descomposición LU

### Introducción
Es posible demostrar que cualquier matriz cuadrada $\mathbf{A}$ puede expresarse como producto de una matriz triangular inferior $\mathbf{L}$ y una matriz triangular superior $\mathbf{U}$:
$$
\mathbf{A} = \mathbf{LU}
$$
El proceso de calcular $\mathbf{L}$ y $\mathbf{U}$ para una determinada matriz $\mathbf{A}$ se conoce como *descomposición LU* o *factorización LU*. Esta descomposición LU no es única (las combinaciones de $\mathbf{L}$ y $\mathbf{U}$ para una cierta matriz $\mathbf{A}$ son infinitas), a menos que se impongan ciertas restricciones a $\mathbf{L}$ o $\mathbf{U}$. Estas restricciones distinguen un tipo de descomposición de otro. En la tabla siguiente se recogen las descomposiciones que estudiaremos en esta sección:

<center>

|         Nombre             |                Restricciones            |
|----------------------------|-----------------------------------------|
|Descomposición de Doolittle | $L_{ii} = 1, \quad i = 1, 2, \dots , n$ |
|Descomposición de Choleski	 | $\mathbf{L} = \mathbf{U}^T$             |

</center>

Después de descomponer $\mathbf{A}$, es fácil resolver el sistema $\mathbf{Ax} = \mathbf{b}$. Primero se reescribe el sistema como $\mathbf{LUx} = \mathbf{b}$. Haciendo $\mathbf{Ux} = \mathbf{y}$, el sistema de ecuaciones se convierten en
$$
\mathbf{Ly} = \mathbf{b}
$$
que puede resolverse para $\mathbf{y}$ mediante una sustitución hacia adelante. Entonces
$$
\mathbf{Ux} = \mathbf{y}
$$
permitirá calcular $\mathbf{x}$ por el proceso de sustitución hacia atrás.

La ventaja de la descomposición LU sobre el método de eliminación de Gauss es que una vez descompuesto $\mathbf{A}$, podemos resolver $\mathbf{Ax} = \mathbf{b}$ para tantos vectores constantes $\mathbf{b}$ como queramos. El coste de cada solución adicional es relativamente pequeño, porque las operaciones de sustitución hacia delante y hacia atrás consumen mucho menos tiempo que el proceso de descomposición.

### Método de descomposición de Doolittle
#### Fase de descomposición.

La descomposición de Doolittle está estrechamente relacionada con la eliminación de Gauss. Para ilustrar la relación, consideremos una matriz $\mathrm{A}$ de $3 \times 3$ y supongamos que existen matrices triangulares
$$
\mathbf{L}=\left[\begin{array}{ccc}
1 & 0 & 0 \\
L_{21} & 1 & 0 \\
L_{31} & L_{32} & 1
\end{array}\right] \quad \mathbf{U}=\left[\begin{array}{ccc}
U_{11} & U_{12} & U_{13} \\
0 & U_{22} & U_{23} \\
0 & 0 & U_{33}
\end{array}\right]
$$
tal que $\mathrm{A} = \mathrm{LU}$. Multiplicando obtenemos:
$$
\mathbf{A}=\left[\begin{array}{lll}
U_{11} & U_{12} & U_{13} \\
U_{11} L_{21} & U_{12} L_{21}+U_{22} & U_{13} L_{21}+U_{23} \\
U_{11} L_{31} & U_{12} L_{31}+U_{22} L_{32} & U_{13} L_{31}+U_{23} L_{32}+U_{33}
\end{array}\right]
$$
Apliquemos ahora la eliminación de Gauss a la ecuación (2.12). La primera pasada del procedimiento de eliminación consiste en elegir la primera fila como fila pivote y aplicar las siguientes operaciones elementales:
$$
\begin{aligned}
\operatorname{fila} 2 & \leftarrow \operatorname{fila} 2 - L_{21} \times \operatorname{fila} 1 \quad \left(\text {elimina } A_{21}\right) \\
\operatorname{fila} 3 & \leftarrow \operatorname{fila} 3 - L_{31} \times \operatorname{fila} 1 \quad  \left( \text {elimina } A_{31} \right) \\
\end{aligned}
$$
Obteniéndose
$$
\begin{aligned}
\mathbf{A}^{\prime} &=\left[\begin{array}{ccc}
U_{11} & U_{12} & U_{13} \\
0 & U_{22} & U_{23} \\
0 & U_{22} L_{32} & U_{23} L_{32}+U_{33}
\end{array}\right]
\end{aligned}
$$
En la siguiente pasada tomamos la segunda fila como fila pivote, y hacemos la siguiente operación:
$$
\operatorname{fila} 3 \leftarrow \operatorname{fila} 3 - L_{32} \times \operatorname{fila} 2 \quad \left(\text {elimina } A_{32}\right)
$$
obteniendo finalmente:
$$
\mathbf{A}^{\prime \prime}=\mathbf{U}=\left[\begin{array}{ccc}
U_{11} & U_{12} & U_{13} \\
0 & U_{22} & U_{23} \\
0 & 0 & U_{33}
\end{array}\right]
$$

El ejemplo anterior revela dos características importantes de la descomposición de Doolittle:

1.	La matriz $\mathbf{U}$ es idéntica a la matriz triangular superior que resulta de la eliminación de Gauss.
2.	Los elementos no diagonales de $\mathbf{L}$ son los multiplicadores de la ecuación pivote utilizados durante la eliminación de Gauss; es decir, $L_{ij}$ es el multiplicador que eliminó $A_{ij}$ .

Es una práctica habitual almacenar los multiplicadores en la parte triangular inferior de la matriz de coeficientes, sustituyendo los coeficientes a medida que se eliminan ($L_{ij}$ sustituyendo a los $A_{ij}$ ). La diagonal de $\mathbf{L}$ no tienen que ser almacenada, porque se entiende todos sus valores son $1$. La forma final de la matriz de coeficientes sería por tanto la siguiente mezcla de $\mathbf{L}$ y $\mathbf{U}$:
$$
[\mathbf{L} \backslash \mathbf{U}]=\left[\begin{array}{lll}
U_{11} & U_{12} & U_{13} \\
L_{21} & U_{22} & U_{23} \\
L_{31} & L_{32} & U_{33}
\end{array}\right]
$$

El algoritmo para la descomposición de Doolittle es, por tanto, idéntico al procedimiento de eliminación de Gauss, excepto que cada multiplicador $\lambda$ se almacena ahora en la parte triangular inferior de $\mathbf{A}$.

#### Fase de resolución

Consideremos ahora el procedimiento para obtener la solución de $\mathbf{Ly} = \mathbf{b}$ por sustitución hacia adelante. La forma escalar de las ecuaciones es (recuerda que $L_{ii} = 1$):

$$
\begin{aligned}
y_1=& b_1 \\
L_{21} y_1+y_2=& b_2 \\
\vdots \\
L_{k 1} y_1+L_{k 2} y_2+\cdots+L_{k, k-1} y_{k-1}+y_k=& b_k \\
\vdots
\end{aligned}
$$

Si se resuelve la $k$-ésima ecuación para $y_k$ se obtiene

$$
y_k=b_k-\sum_{j=1}^{k-1} L_{k j} y_j, \quad k=2,3, \ldots, n
$$

Por otro lado, la fase de sustitución hacia atrás para resolver $\mathbf{Ux} = \mathbf{y}$ es idéntica a la utilizada en el método de eliminación de Gauss.


**Ejercicio 6 -** Implementa el método LU para la resolución de sistemas lineales, siguiendo las indicaciones dadas anteriormente. Puedes reutilizar código de los ejercicios anteriores.

In [ ]:
def LU_decomposition(A: np.array, func = row_lineal_comb) -> np.array:

    '''se le pasa la matriz A
    una funcion func que se encargue de hacer al combinacion lineal: A[j] = A[j] - A[i] * k

    objetivo -> A = LU

    la salida es una matriz rectangular U triangular superior y una matriz cuadrada L triangular inferior
    U es la escalonada aplicando gauss
    L contiene los valores de k para calcular la escalonada y una diagonal de 1 para que L * U  = A
    '''
    A_copy = np.copy(A)
    n = len(A_copy)

    L = np.identity((n))


    for i in range(n): #iteramos cada fila
        for j in range(i +1, n): #iteramos solo sobre las filas que estan debajo del pivote
            if A_copy[i, i] == 0:
                continue

            k =  A_copy[j, i]/ A_copy[i, i]

            L[j, i] = k

            A_copy = func(A_copy, i, j, -k)

    U = A_copy
    return L, U, 
    

A = np.array([[4, -2, 1],
             [-2, 4, -2],
             [1, -2, 4]], dtype = float)

b = np.array([11, -16, 17])

L1, U1 = LU_decomposition(A)
print(L1)
print(U1)
# print(L1 + U1)
# print()
# A_ampliada = np.column_stack((A, b))
# L2, U2, = LU_decomposition(A_ampliada)
# print(L2)
# print(U2)

# print()
# print(L2@U2)

# print()
# print(A_ampliada)

# A = np.array([[6, -4, 1],
#               [-4, 6, -4],
#               [1, -4, 6]])

# B = np.array([[-14, 22], 
#               [36, -18],
#               [6, 7]])

# A_concat_B = np.column_stack((A, B))
# L3, U3, = LU_decomposition(A_concat_B)
# print('L3 = \n', L3)
# print()
# print('u3 =  \n', U3)
# print()
# print('Gauss de A y B  \n', gauss_U(A_concat_B))


L3 = 
 [[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [ 0.16666667 -1.          1.        ]]

u3 =  
 [[  6  -4   1 -14  22]
 [  0   3  -3  26  -3]
 [  0   0   2  34   0]]

Gauss de A y B  
 [[  6  -4   1 -14  22]
 [  0   3  -3  26  -3]
 [  0   0   2  34   0]]


In [65]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)  # 1*4 + 2*5 + 3*6 = 32
print(result) 

32


In [66]:
def forward_substitution(L, b):
    """Resuelve Lc = b para c usando sustitución hacia adelante."""
    n = len(b)
    c = np.zeros_like(b, dtype=float)
    for i in range(n):
        c[i] = (b[i] - np.dot(L[i, :i], c[:i])) / L[i, i]
    return c

In [ ]:
def forward_substitution_p_systems(L, B):
    """
    Resuelve L * C = B usando sustitución hacia adelante, 
    donde L es triangular inferior y B es una matriz (varios sistemas).
    """
    n = L.shape[0]  # Tamaño de la matriz
    m = B.shape[1]  # Número de sistemas (columnas de B)
    C = np.zeros_like(B, dtype=float)  # Matriz solución C con mismas dimensiones que B

    # Iterar sobre cada fila
    for i in range(n):
        for j in range(m):  # Iterar sobre cada columna de B
            C[i, j] = (B[i, j] - np.dot(L[i, :i], C[:i, j])) / L[i, i]

    return C


In [50]:
def forward_backward_sustitution(L, U, b, func= backward_sustitusion):
    '''
    the input is a lower trriangular matrix L,
    an upper triangular matrix U,
    yhe solution vector b
    and the function which will be a normal backward sustitusion by default,
    the function of this parameter will be dealing with the second part of fthe solving
    

    reminder: we are searching for x, not y
    '''

    assert len(b) >= 1, 'this method isnt valid for solving multiply ecuation systems'

    #forward sustitutuon
    # Ux = y -> Solve Ly = b

    L_copy = np.copy(L)
    b_copy = np.copy(b)
    y = np.zeros(b.shape)

    for i in range(len(L)):
        total_sum = 0
        for j in range(i, -1, -1):
            total_sum += L_copy[i, j] * y[j]
            # print(f'total sum = {total_sum}')

        y[i] = (b_copy[i] - total_sum) / L_copy[i, i]
        # print(f'y = {y}')

    # print(y)

    #backward sustitution
    # Ux = y

    solution = func(U, y)

    return solution



A = np.array([[4, -2, 1],
             [-2, 4, -2],
             [1, -2, 4]], dtype = float)

b = np.array([11, -16, 17])

B = np.array([[-14, 22], 
              [36, -18],
              [6, 7]])


L1, U1 = LU_decomposition(A)
# print(L1)
# print(U1)

sol = forward_backward_sustitution(L1, U1, b)
sol





array([ 1., -2.,  3.])

### Método de descomposición de Choleski

La descomposición de Choleski $\mathbf{A} = \mathbf{LL}^T$ tiene dos limitaciones:
1. Como $\mathbf{LL}^T$ es siempre una matriz simétrica, **la descomposición de Choleski requiere que $\mathbf{A}$ sea simétrica**.
2. El proceso de descomposición implica tomar las raíces cuadradas de ciertas combinaciones de los elementos de $\mathbf{A}$. Se puede demostrar que para evitar las raíces cuadradas de los números negativos, **$\mathbf{A}$ debe ser definida positiva** (que equivale por ejemplo a exigir que todos sus autovalores sean positivos).

Si se puede lidiar con estas limitaciones, entonces la descomposición de Choleski resulta una de las mejores opciones, ya que requiere aproximadamente la mitad de las operaciones necesarias en comparación con una descomposición LU al uso. Esto se debe a su explotación de la simetría.

A continuación se describe esta descomposición

$$
\mathbf{A}=\mathbf{L L}^T
$$

de una matriz $3 \times 3$:

$$
\left[\begin{array}{lll}
A_{11} & A_{12} & A_{13} \\
A_{21} & A_{22} & A_{23} \\
A_{31} & A_{32} & A_{33}
\end{array}\right]=\left[\begin{array}{ccc}
L_{11} & 0 & 0 \\
L_{21} & L_{22} & 0 \\
L_{31} & L_{32} & L_{33}
\end{array}\right]\left[\begin{array}{ccc}
L_{11} & L_{21} & L_{31} \\
0 & L_{22} & L_{32} \\
0 & 0 & L_{33}
\end{array}\right]
$$
Después de realizar la multiplicación del lado derecho, obtenemos
$$
\left[\begin{array}{lll}
A_{11} & A_{12} & A_{13} \\
A_{21} & A_{22} & A_{23} \\
A_{31} & A_{32} & A_{33}
\end{array}\right]=\left[\begin{array}{lll}
L_{11}^2 & L_{11} L_{21} & L_{11} L_{31} \\
L_{11} L_{21} & L_{21}^2+L_{22}^2 & L_{21} L_{31}+L_{22} L_{32} \\
L_{11} L_{31} & L_{21} L_{31}+L_{22} L_{32} & L_{31}^2+L_{32}^2+L_{33}^2
\end{array}\right]
$$

Nótese que la matriz del lado derecho es simétrica, como se ha señalado anteriormente. Igualando las matrices $\mathbf{A}$ y $\mathbf{LL}^T$ elemento a elemento, obtenemos seis ecuaciones (por simetría sólo hay que considerar los elementos triangulares inferiores o superiores) en función de los seis coeficientes desconocidos de $\mathbf{L}$. Resolviendo estas ecuaciones en un cierto orden, es posible obtener sólo una incógnita en cada ecuación.

Consideremos la parte triangular inferior de las matrices de la ecuación anterior (la parte triangular superior también serviría). Igualando los elementos de la primera columna, empezando por la primera fila y procediendo hacia abajo, podemos calcular $L_{11}$ , $L_{21}$ , y $L_{31}$ en ese orden:

$$
\begin{array}{ll}
A_{11}=L_{11}^2 & L_{11}=\sqrt{A_{11}} \\
A_{21}=L_{11} L_{21} & L_{21}=A_{21} / L_{11} \\
A_{31}=L_{11} L_{31} & L_{31}=A_{31} / L_{11}
\end{array}
$$

La segunda columna, a partir de la segunda fila, permite calcular $L_{22}$ y $L_{32}$:
$$
\begin{array}{ll}
A_{22}=L_{21}^2+L_{22}^2 & L_{22}=\sqrt{A_{22}-L_{21}^2} \\
A_{32}=L_{21} L_{31}+L_{22} L_{32} & L_{32}=\left(A_{32}-L_{21} L_{31}\right) / L_{22}
\end{array}
$$

Por último de la tercera columna y tercera fila obtenemos da $L_{33}$:

$$
A_{33}=L_{31}^2+L_{32}^2+L_{33}^2 \quad L_{33}=\sqrt{A_{33}-L_{31}^2-L_{32}^2}
$$

Ahora podemos extrapolar los resultados para una matriz $n \times n$ cualquiera. Se observa que un elemento genérico de la parte triangular inferior de $\mathbf{L L}^T$ tendrá la forma:

$$
\left(\mathbf{L L}^T\right)_{i j}=L_{i 1} L_{j 1}+L_{i 2} L_{j 2}+\cdots+L_{i j} L_{j j}=\sum_{k=1}^j L_{i k} L_{j k}, \quad i \geq j
$$

Al igualar este término con el elemento correspondiente de $\mathbf{A}$ se obtiene

$$
A_{i j}=\sum_{k=1}^j L_{i k} L_{j k}, \quad i=j, j+1, \ldots, n, \quad j=1,2, \ldots, n
$$

El rango de índices mostrado limita los elementos a la parte triangular inferior. Para la primera columna ($j = 1$), de la ecuación anterior obtenemos:

$$
L_{11}=\sqrt{A_{11}} \quad L_{i 1}=A_{i 1} / L_{11}, \quad i=2,3, \ldots, n
$$

Al pasar a otras columnas, observamos que la incógnita es $L_{ij}$ (los demás elementos de $\mathbf{L}$ que aparecen en la ecuación ya se han calculado). Tomando el término que contiene $L_{ij}$ fuera de la suma, se obtiene:

$$
A_{i j}=\sum_{k=1}^{j-1} L_{i k} L_{j k}+L_{i j} L_{j j}
$$

Si $i = j$ (elemento de la diagonal), la solución es

$$
L_{j j}=\sqrt{A_{j j}-\sum_{k=1}^{j-1} L_{j k}^2}, \quad j=2,3, \ldots, n
$$

Y para elementos fuera de la diagonal:

$$
L_{i j}=\left(A_{i j}-\sum_{k=1}^{j-1} L_{i k} L_{j k}\right) / L_{j j}, \quad j=2,3, \ldots, n-1, \quad i=j+1, j+2, \ldots, n
$$

#### Otras consideraciones sobre este algoritmo

Observa en el desarrollo anterior que $A_{ij}$ sólo aparece en la fórmula de $L_{ij}$. Por lo tanto, una vez que $L_{ij}$ ha sido calculado, el correspondiente $A_{ij}$ no será usado de nuevo. Esto permite escribir los elementos de $\mathbf{L}$ sobre la parte triangular inferior de $\mathbf{A}$ a medida que se calculan. Los elementos por encima de la diagonal principal de $\mathbf{A}$ permanecerán intactos. 

Ten en cuenta también que, una vez descompuesta la matriz de coeficientes $\mathbf{A}$, la solución de $\mathbf{Ax} = \mathbf{b}$ puede obtenerse mediante las operaciones habituales de sustitución hacia delante y hacia atrás. 

In [127]:
#teoria numpy
import numpy as np

# Definir la matriz
A = np.array([[4, 2],
              [1, 3]])

#autovalores = np.linalg.eig(A)[0]

# Calcular los autovalores y autovectores
autovalores, autovectores = np.linalg.eig(A)

# Imprimir resultados
print("Autovalores:", autovalores)   # Valores propios
print("Autovectores:\n", autovectores)  # Vectores propios



Autovalores: [5. 2.]
Autovectores:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
[5. 2.]


**Ejercicio 7 -** Programa una función que implemente la descomposición de Choleski. Si se encuentra un término diagonal negativo durante la descomposición, se debe imprime un mensaje de error y se debe termina el programa.

In [ ]:
def choleski_decomposition(A):
    '''
    the input is a symetric and positive defined matrix A, otherwise an assert will raise an error.
    '''

    if not np.array_equal(A, A.T):
        raise ValueError("matrix A isnt symetric")
    
    if not np.all(np.linalg.eigvals(A) > 0):
        raise ValueError("matriz A isnt positive defined")

    L = np.zeros(A.shape)

    for i in range(0, len(A)):
        for j in range(i+1):
            total_sum = 0
            for k in range(j):
                total_sum += L[i, k] * L[j, k]
                
            if i == j: 
                L[j, j] = (A[i, j] - total_sum) ** 0.5
            else: 
                L[i, j] = (A[i, j] - total_sum) / L[j, j]
    return L

A = np.array([[4, 2, 2],
              [2, 6, 2],
              [2, 2, 5]], dtype=float)


choleski_decomposition(A)


array([[2.        , 0.        , 0.        ],
       [1.        , 2.23606798, 0.        ],
       [1.        , 0.4472136 , 1.94935887]])

**Ejercicio 8 -** Programa una función que, dada una descomposición de Choleski, obtenga la solución del sistema.

In [68]:
A = np.array([[4, -2, 2],
            [-2, 2, -4],
            [2, -4, 11]], dtype=float)

L = choleski_decomposition(A)
L

array([[ 2.,  0.,  0.],
       [-1.,  1.,  0.],
       [ 1., -3.,  1.]])

**Ejercicio 9 -** Operando a mano, utiliza el método de descomposición de Doolittle para resolver el sistema de ecuaciones $\mathbf{Ax} = \mathbf{b}$, donde

$$
\mathbf{A}=\left[\begin{array}{rrr}
1 & 4 & 1 \\
1 & 6 & -1 \\
2 & -1 & 2
\end{array}\right] \quad \mathbf{b}=\left[\begin{array}{r}
7 \\
13 \\
5
\end{array}\right]
$$


**Ejercicio 10 -** Operando a mano, calcular la descomposición de Choleski de la matriz:
$$
A=\left[\begin{array}{rrr}
4 & -2 & 2 \\
-2 & 2 & -4 \\
2 & -4 & 11
\end{array}\right]
$$

**Ejercicio 11 -** Escribe un programa que resuelva $\mathbf{Ax} = \mathbf{B}$ con el método de descomposición de Doolittle y calcula $\left| \mathbf{A} \right|$. Utiliza las funciones programadas en ejercicios anteriores. Testea tu programa con las siguientes matrices
$$
\mathbf{A}=\left[\begin{array}{rrr}
3 & -1 & 4 \\
-2 & 0 & 5 \\
7 & 2 & -2
\end{array}\right] \quad \mathbf{B}=\left[\begin{array}{rr}
6 & -4 \\
3 & 2 \\
7 & -5
\end{array}\right]
$$

**Ejercicio 12 -** Escribe un programa que resuelva $\mathbf{Ax} = \mathbf{B}$ con el método de descomposición de Doolittle y calcula $\left| \mathbf{A} \right|$. Utiliza las funciones programadas en ejercicios anteriores. Testea tu programa con las siguientes matrices
$$
\mathbf{A}=\left[\begin{array}{rrr}
3 & -1 & 4 \\
-2 & 0 & 5 \\
7 & 2 & -2
\end{array}\right] \quad \mathbf{B}=\left[\begin{array}{rr}
6 & -4 \\
3 & 2 \\
7 & -5
\end{array}\right]
$$

**Ejercicio 13 -** Resuelve mediante el método de descomposición de Choleski el sistema de ecuaciones definido por las siguientes matrices. Utiliza las funciones programadas en ejercicios anteriores. La solución debe ser: $\mathbf{x} = \left[ 3.09212567, -0.73871706, -0.8475723, 0.13947788 \right]$

$$
\mathbf{A}=\left[\begin{array}{rrrr}
1.44 & -0.36 & 5.52 & 0.00 \\
-0.36 & 10.33 & -7.78 & 0.00 \\
5.52 & -7.78 & 28.40 & 9.00 \\
0.00 & 0.00 & 9.00 & 61.00
\end{array}\right] \quad \mathbf{b}=\left[\begin{array}{r}
0.04 \\
-2.15 \\
0 \\
0.88
\end{array}\right]
$$

In [70]:
A = np.array([[1.44, -0.36, 5.52, 0.00],
            [-0.36, 10.33, -7.78, 0.00],
            [5.52, -7.78, 28.40, 9.00],
            [0.00, 0.00, 9.00, 61.00]], dtype=float)

b = np.array([0.04, -2.15, 0.00, 0.88], dtype=float)

L_13 = choleski_decomposition(A)
L_13

array([[ 1.2,  0. ,  0. ,  0. ],
       [-0.3,  3.2,  0. ,  0. ],
       [ 4.6, -2. ,  1.8,  0. ],
       [ 0. ,  0. ,  5. ,  6. ]])

In [71]:
forward_backward_sustitution(L_13, L_13.T, b)

array([ 3.09212567, -0.73871706, -0.8475723 ,  0.13947788])