Las **matrices sparse** (o matrices dispersas) son matrices que contienen un alto porcentaje de elementos con valor cero. Estas matrices son comunes en aplicaciones como la resolución de ecuaciones diferenciales, grafos, redes y modelado matemático.

### Características principales:
1. **Alta dispersión**: La mayoría de los elementos son ceros, lo que significa que los valores diferentes de cero están dispersos en la matriz.
2. **Eficiencia en memoria**: En lugar de almacenar todos los elementos, se almacenan únicamente los valores no cero y sus ubicaciones, lo que reduce significativamente el uso de memoria.
3. **Operaciones especializadas**: Las operaciones matemáticas en matrices dispersas utilizan algoritmos optimizados que aprovechan la estructura dispersa para mejorar el rendimiento.

### Representaciones comunes:
1. **Lista de coordenadas (COO)**:
   - Se almacenan tres arreglos: uno para las filas, otro para las columnas y uno más para los valores diferentes de cero.
2. **Compressed Sparse Row (CSR)**:
   - Se almacena una lista de valores no cero, los índices de las columnas y un arreglo adicional que indica dónde comienza cada fila.
3. **Compressed Sparse Column (CSC)**:
   - Similar a CSR, pero organizado por columnas en lugar de filas.


### Ventajas de usar matrices sparse:
- **Reducción de memoria**: Útil para trabajar con datos de gran tamaño.
- **Mayor velocidad**: Operaciones más rápidas en aplicaciones especializadas.
- **Aplicaciones específicas**: Redes sociales, sistemas de recomendación, problemas de optimización, entre otros.

Sin embargo, en ciertos casos, las operaciones pueden ser menos eficientes si la matriz no es lo suficientemente dispersa.

---
Para representar la matriz dispersa dada:


\begin{bmatrix}
0 & 0 & 3 \\
0 & 0 & 0 \\
4 & 0 & 0 \\
\end{bmatrix}


Con los métodos más comunes para trabajar con matrices dispersas (\( COO \), \( CSR \), \( CSC \)), la representación sería la siguiente:


### 1. **Formato COO (Coordinate List):**
En este formato, almacenamos tres listas: las filas, las columnas y los valores correspondientes a los elementos no cero.

In [3]:
rows = [0, 2]         # Índices de las filas
cols = [2, 0]         # Índices de las columnas
values = [3, 4]       # Valores no cero

### 2. **Formato CSR (Compressed Sparse Row):**
En este formato, organizamos los datos fila por fila. Se utilizan tres arreglos:
1. **Valores**: Los elementos diferentes de cero.
2. **Índices de columnas**: La columna correspondiente a cada valor.
3. **Punteros de fila**: Indica dónde comienza cada fila en las listas de valores e índices de columna.

In [2]:
values = [3, 4]              # Valores no cero
col_indices = [2, 0]         # Índices de columnas
row_pointers = [0, 1, 1, 2]  # Punteros de fila: inicio de cada fila en `values`

# Explicación de row_pointers:
# - 0 indica que la fila 0 empieza en el índice 0 de `values`.
# - 1 indica que la fila 1 empieza y termina en el índice 1 (sin valores).
# - 2 indica que la fila 2 empieza en el índice 1 y termina en el índice 2 de `values`.

### 3. **Formato CSC (Compressed Sparse Column):**
Este formato es similar al CSR, pero organizado columna por columna. Los arreglos son:
1. **Valores**: Elementos diferentes de cero.
2. **Índices de filas**: La fila correspondiente a cada valor.
3. **Punteros de columna**: Indica dónde comienza cada columna en las listas de valores e índices de fila.

In [1]:
values = [4, 3]              # Valores no cero (ordenados por columna)
row_indices = [2, 0]         # Índices de filas
col_pointers = [0, 0, 1, 2]  # Punteros de columna: inicio de cada columna en `values`

# Explicación de col_pointers:
# - 0 indica que la columna 0 no tiene valores.
# - 0 indica que la columna 1 no tiene valores.
# - 1 indica que la columna 2 empieza en el índice 1 de `values` y termina en el índice 2.

### implementacion por diccionarios

In [3]:
sparse_matrix = {
    (0, 2): 3,
    (2, 0): 4
}

value = sparse_matrix.get((0, 2))  
print(value)
value = sparse_matrix.get((1, 1), 'no existe')  
print(value)

3
no existe


In [4]:
sparse_diag_dominant = {
    (0, 0): 10, (0, 1): 1, (0, 2): 0, (0, 3): -1,
    (1, 0): 2, (1, 1): 20, (1, 2): -3, (1, 3): 4,
    (2, 0): 0, (2, 1): -2, (2, 2): 15, (2, 3): 1,
    (3, 0): 1, (3, 1): 0, (3, 2): 1, (3, 3): 12
}

sparse_with_zero = {
    (0, 0): 10, (0, 1): 2, (0, 2): -1, (0, 3): 3,
    (1, 0): 4, (1, 1): 0,  (1, 2): 1,  (1, 3): 5,
    (2, 0): -1, (2, 1): 3, (2, 2): 8,  (2, 3): 0,
    (3, 0): 2, (3, 1): 4, (3, 2): -2, (3, 3): 9
}

In [5]:
max_row = 0
max_col = 0

for i, j in sparse_diag_dominant.keys():
    max_row = max(max_row, i)
    max_col = max(max_col, j)
    
print(max_row +1, max_col +1)

4 4


In [8]:
for i in range(max_col + 1):  # Asumiendo que max_col ya está definido
    if sparse_with_zero.get((i, i), 0) == 0:  # Verifica si (i, i) es 0 o no está definido
        print(f"Tiene un 0 en la diagonal en la posición ({i}, {i})")

Tiene un 0 en la diagonal en la posición (1, 1)


In [22]:
import random

In [47]:
def generate_sparse_matrix(size=10):
    sparse_matrix = {}
    for i in range(size):
        for j in range(size):
            if i == j:
                # Diagonal: valores no nulos (10 a 30)
                value = random.choices([0, random.randint(1, 10)], weights=[0.1, 0.9])[0]
            else:
                # Fuera de la diagonal: mayor probabilidad de ser cero
                value = random.choices([0, random.randint(1, 5)], weights=[0.7, 0.3])[0]
            if value != 0:
                sparse_matrix[(i, j)] = value
    return sparse_matrix

# Generar vector b
def generate_vector_b(size=10):
    return [random.uniform(1.0, 20.0) for _ in range(size)]

In [48]:
matrix = generate_sparse_matrix(5)
matrix

{(0, 0): 4,
 (0, 1): 2,
 (1, 1): 10,
 (1, 2): 4,
 (1, 4): 3,
 (2, 1): 5,
 (2, 2): 3,
 (3, 0): 4,
 (3, 3): 10,
 (3, 4): 5,
 (4, 0): 1,
 (4, 4): 3}

In [41]:
for i in range(5):
    for j in range(5):
        value = matrix.get((i, j))
        if value == None:
            continue
        else: print(value)


9
2
9
5
2
4
1
1
7


In [49]:
b = generate_vector_b(5)
b

[19.65016120295794,
 10.288801748739468,
 12.919701048447536,
 19.707553410351345,
 2.0551197104466086]

In [35]:
import numpy as np

def reconstruct_matrix_numpy(sparse_matrix, size):
    # Crear una matriz completa de ceros
    full_matrix = np.zeros((size, size), dtype=int)
    # Asignar los valores del diccionario a la matriz
    for (i, j), value in sparse_matrix.items():
        full_matrix[i, j] = value
    return full_matrix


size = 5  
full_matrix = reconstruct_matrix_numpy(matrix, size)

# Imprimir la matriz reconstruida
full_matrix


array([[9, 2, 0, 0, 0],
       [0, 9, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [2, 0, 0, 4, 1],
       [0, 0, 0, 1, 7]])

In [60]:
def iter_esq(A: dict, x, b, omega):

    n = len(b)
    x_old = np.copy(x)

    for i in range(n):
        x[i] = b[i] 

        for j in range(n):
            if j == i:
                continue # si i = j se salta esta iteracion

            A_ij = A.get((i, j))
            if A_ij is not None:
                x[i] -= A_ij * x[j]

        A_ii = A.get((i, i))
        if A_ii is None:
            raise ValueError(f"element in diagonal A[{i}, {i}] isnt defined.")
        
        x[i] *= omega / A_ii
        x[i] += (1 - omega) * x_old[i]
        
    return x

def solve_gaus_seidel_spars(        
        A: np.ndarray | dict,
        x: np.ndarray,
        b: np.ndarray | list,
        omega: float,
        tol: float,
        max_n_ite: int) -> np.ndarray :
    
    for i in range(1, max_n_ite):

        # guardo el candidato actual para comparar
        x_old = np.copy(x)

        # aaplicar el sistema iterativo de gauss seidel

        x = iter_esq(A, x, b, omega)

        #comprobar lo de la tolerancia

        dx = np.linalg.norm(x - x_old) # normal euclidea
        
        error = dx / np.linalg.norm(x)


        if error < tol:

            return x, i, omega
        
    print(f" cuidadillo: la tolerancia objetivo no ha sido alcanzada. la solucion actual tiene un error de {error}")

    return x, i, omega
    


In [67]:
matrix_dic = generate_sparse_matrix(5)
print(matrix_dic)
b_example = generate_vector_b(5)
print(b_example)

matrix_example= reconstruct_matrix_numpy(matrix_dic, 5)
print(matrix_example)

sol_numpy = np.linalg.solve(matrix_example, b_example)
sol_numpy

{(0, 0): 10, (0, 3): 4, (0, 4): 4, (1, 0): 4, (1, 2): 2, (2, 2): 5, (2, 4): 4, (3, 1): 1, (3, 3): 5, (3, 4): 3, (4, 4): 7}
[4.367598269182446, 11.668407957957527, 18.725726843586074, 12.352101763084834, 17.488961240361846]
[[10  0  0  4  4]
 [ 4  0  2  0  0]
 [ 0  0  5  0  4]
 [ 0  1  0  5  3]
 [ 0  0  0  0  7]]


array([ 2.04389852, 37.43818148,  1.74640694, -6.51626976,  2.49842303])

In [68]:
matrix_dic_zeros = generate_sparse_matrix(5)
print(matrix_dic)
b_example_2 = generate_vector_b(5)
print(b_example)

matrix_example= reconstruct_matrix_numpy(matrix_dic_zeros, 5)
print(matrix_example)


{(0, 0): 10, (0, 3): 4, (0, 4): 4, (1, 0): 4, (1, 2): 2, (2, 2): 5, (2, 4): 4, (3, 1): 1, (3, 3): 5, (3, 4): 3, (4, 4): 7}
[12.35595057412507, 11.296801945445631, 15.312261563813774, 19.693735577944118, 2.5654471612161878]
[[3 0 0 0 1]
 [0 0 0 1 5]
 [0 0 2 0 0]
 [0 0 2 0 0]
 [0 1 0 1 8]]


In [65]:
x = np.array([0.0, 0.0, 0.0, 0.0, 0.0])
omega = 0.7
tol = 10 ** -6
max_ite = 1000

print(b_example)

solution = solve_gaus_seidel_spars(matrix_dic, x, b_example, omega, tol, max_ite)
print(f'solution \n: {solution}')

[8.397484736508543, 9.440626357247968, 14.03424525545538, 9.463110120817575, 14.529298095394578]
solution 
: (array([1.12352561, 0.49684813, 1.93391371, 1.65633512, 1.52306732]), 19, 0.7)


In [69]:
solution = solve_gaus_seidel_spars(matrix_dic_zeros, x, b_example, omega, tol, max_ite)
print(f'solution \n: {solution}')

ValueError: element in diagonal A[1, 1] isnt defined.